thold sql optimization
Cacti/plugin_thold pull request #127
Opened 2017-10-12 14:20 UTC by rgt0078

Hello
Here is a means to optimize thold execution (see https://github.com/Cacti/plugin_thold/issues/126)
Regards

2017-10-12 15:24 UTC, ikorzha commented
I have tested the changes you proposed on my prod system:
I get thousands of errors in the log see below:
![thold-daemon](https://user-images.githubusercontent.com/11211789/31504195-c20ed9be-af3f-11e7-9f03-448f9cb89dc6.jpg)

2017-10-12 15:55 UTC, rgt0078 commented
Sorry I fixed the cases where this function is called outside includes/polling.php (same behavior than before)

2017-10-12 19:19 UTC, ikorzha commented
No more errors after latest commit, thank you. I do want to ask you, after I have applied the change I do not see any thold daemon improvements at all. I do not use standard thold poller as it is insufficient for the size of my install.
![thold-daemon-poller](https://user-images.githubusercontent.com/11211789/31514735-9e04f2da-af60-11e7-89d7-0096a23aeadf.jpg)

Any comments or improvements we can squeeze there too?

2017-10-12 23:58 UTC, cigamit requested changes
Check my comments, make the changes, re-push, and thank you for taking the time.

2017-10-12 23:58 UTC, cigamit commented on includes/polling.php
> +			$sql_query = "SELECT td.*, dtr.data_source_name, h.hostname, h.description, h.notes, h.snmp_engine_id
put the h.hostname ... on a second line.  Same with the other examples.  Indent with hard tabs.

2017-10-12 23:58 UTC, cigamit commented on includes/polling.php
> +				AND td.tcheck = 1 AND h.status=3";
Put the AND ... on it's own line.

2017-10-12 23:58 UTC, cigamit commented on thold_functions.php
> +	/* this request is useless !?!
Just remove it then.

2017-10-13 07:22 UTC, rgt0078 commented
Hi,
I inserted the same optimization in case of use of thold as a daemon...
Rgds

2017-10-13 12:32 UTC, ikorzha commented
Thank you for your optimization, I have tested it with thold daemon. I do see a slight improvement on thold daemon now. Thank you for your improvements. Hopefully Cigamit will merge the changes in.

2017-11-12 12:56 UTC, merged

2017-11-12 13:03 UTC, cigamit commented
Screwed up the merge, but it's fixed now.