RPN Comparsion operator's results are wrong
Cacti/plugin_thold pull request #206
Opened 2018-09-12 06:04 UTC by hoder38

Variable 1 and variable 2 in the function thold_expression_compare_rpn need to swap, otherwise the result of LT, LE, GT, GE will be wrong.

2018-09-12 06:35 UTC, netniV commented
I need to give THold a thorough review at some point.  Your logic seems sound, have you the data that proves this to be true?

2018-09-12 07:09 UTC, hoder38 commented
Before the change will be V2, V1, LT  (V2 < V1)
              V1
In stack: V2   pop  V1  pop V2 => V1 < V2

So it's needed to swap the V1 and V2 => V1, V2, LT (V1 < V2)
              V2
In stack: V1   pop  V2  pop  V1 => V1 < V2

2018-09-12 07:45 UTC, netniV commented
Cool. I’ll run a quick test later and then commit if successful

2018-09-12 12:51 UTC, netniV commented
So, my tests suggest that THOLD is working as expected with RPN's:
```
13,3,+,4,/: 4
2,4,*: 8
10,20,GT: 0
10,20,LT: 1
20,10,GT: 1
20,10,LT: 0
20,20,LE: 1
20,20,GE: 1
20,10,GT,2,3,IF: 2
20,10,LT,2,3,IF: 3
```
This would suggest that you have an issue with the RPN you are using.

2018-09-12 12:55 UTC, netniV requested changes
Please provide more evidence that this is wrong.

2018-09-17 06:13 UTC, hoder38 commented
![img_20180917_140129676](https://user-images.githubusercontent.com/10161940/45608007-bb8e9a80-ba82-11e8-9dbf-fca937bd363e.png)
When I use the "console -> threshold Templates", "Data manipulation" -> "Data type" choose "RPN Expression", the results of LT, LE, GT, GE like I said will be wrong.
Would you tell me how did you test THOLD with RPN

ps. sorry for the phone shot, it's in the private internet

2018-09-17 07:21 UTC, netniV commented
I tested the functions directly.  My only question is whether there is something to do with the order it put the data source/value that you are specifying.  What exact expression were you using as it is empty above?

2018-09-17 09:30 UTC, hoder38 commented
![img_20180917_140129676](https://user-images.githubusercontent.com/10161940/45615118-31542f80-ba9e-11e8-9448-e4cd240e8c4c.jpg)

The parameter order is important in LT, GT, LE, GE.

A > B   != B > A

I use "10,20,LT", and it will be "0"

2018-09-17 11:06 UTC, netniV commented
That's incorrect.  10 *is* less than 20 so the value will be 1.

2018-09-17 11:22 UTC, hoder38 commented
Yes, this is before the commitment.

After the correction it will be 1.

2018-09-17 11:23 UTC, netniV commented
No, see my posting above.  10,20,LT is 1 in the current code.

2018-09-17 11:31 UTC, hoder38 commented
Did you use the Threshold Template?

Maybe the passing of the parameters is wrong

2018-12-28 22:46 UTC, merged