Fix filtering on Ack Required field
Cacti/plugin_thold pull request #395
Opened 2019-12-11 01:43 UTC by aleksashka

Ack Required filtering does not work (extra ')' in SQL query).

2019-12-16 14:12 UTC, netniV requested changes
Change looks good, can you update the CHANGELOG

2019-12-17 13:25 UTC, netniV requested changes
Thanks, needs an issue number though, likely 395 if you only have the pull request open.

2019-12-18 05:47 UTC, aleksashka commented
Sorry for so many iterations - hope this one is finally good enough :).

2019-12-18 16:58 UTC, netniV approved these changes

2019-12-18 16:58 UTC, merged